#!/usr/bin/env python3
"""Scaffold autoresearch session files from validated primitives."""

from __future__ import annotations

import argparse
import json
import re
import shlex
from datetime import datetime, timezone
from pathlib import Path


SESSION_FILES = [
    "autoresearch.md",
    "autoresearch.sh",
    "autoresearch.jsonl",
    "autoresearch.ideas.md",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", default=".", help="Session directory")
    parser.add_argument("--goal", required=True)
    parser.add_argument("--scope", action="append", required=True)
    parser.add_argument("--metric-name", required=True)
    parser.add_argument("--metric-unit", default="")
    parser.add_argument("--direction", choices=["lower", "higher"], required=True)
    parser.add_argument("--verify-command", required=True)
    parser.add_argument("--guard-command")
    parser.add_argument("--max-iterations", type=int)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def metric_name_is_safe(name: str) -> bool:
    return re.fullmatch(r"[\w.µ-]+", name) is not None


def refuse_overwrite(root: Path, force: bool) -> None:
    if force:
        return
    existing = [name for name in SESSION_FILES + ["autoresearch.checks.sh"] if (root / name).exists()]
    if existing:
        joined = ", ".join(existing)
        raise SystemExit(f"Refusing to overwrite existing session files: {joined}. Use --force.")


def write_executable(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | 0o755)


def render_md(args: argparse.Namespace) -> str:
    editable = "\n".join(f"- `{scope}`" for scope in args.scope)
    guard = "`./autoresearch.checks.sh`" if args.guard_command else "none"
    iterations = str(args.max_iterations) if args.max_iterations else "unbounded until interrupted or plateau"
    return f"""# Autoresearch: {args.goal}

## Objective
{args.goal}

## Metric
- Primary: `{args.metric_name}` ({args.metric_unit or "unitless"}, {args.direction} is better)
- Verify: `./autoresearch.sh`
- Guard: {guard}
- Iterations: {iterations}

## Scope
### Editable
{editable}

### Read-only
- Session files may be updated for logging and resume context.
- Guard/test files are read-only during optimization unless the session goal explicitly targets them.

### Off limits
- Secrets, credentials, caches, generated dependency folders, and unrelated dirty worktree changes.

## Constraints
- Make one logical change per iteration.
- Prefer simpler code when the metric is equal.
- Keep improvements only when the primary metric improves and guard checks pass.
- Record every result in `autoresearch.jsonl` with a short description and useful ASI.

## What's Been Tried
- Baseline not yet run.

## Next Ideas
- Establish the baseline.
- Read the highest-impact files in scope and choose the first narrow hypothesis.
"""


def render_runner(args: argparse.Namespace) -> str:
    command = shlex.quote(args.verify_command)
    metric = args.metric_name
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by autoresearch-plan. Keep output concise and deterministic.
raw_output="$(bash -lc {command})"
printf '%s\\n' "$raw_output"

if printf '%s\\n' "$raw_output" | grep -Eq '^METRIC[[:space:]]+{re.escape(metric)}='; then
  exit 0
fi

value="$(printf '%s\\n' "$raw_output" | awk 'NF {{ last=$0 }} END {{ print last }}' | tr -d '[:space:]')"
python3 - "$value" "{metric}" <<'PY'
import math
import sys

value_text, metric_name = sys.argv[1], sys.argv[2]
try:
    value = float(value_text)
except ValueError:
    print(f"Metric extraction failed: expected one numeric value, got {{value_text!r}}", file=sys.stderr)
    sys.exit(2)
if not math.isfinite(value):
    print(f"Metric extraction failed: non-finite value {{value_text!r}}", file=sys.stderr)
    sys.exit(2)
print(f"METRIC {{metric_name}}={{value}}")
PY
"""


def render_checks(args: argparse.Namespace) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated by autoresearch-plan. Guard time does not count toward the primary metric.
{args.guard_command}
"""


def main() -> int:
    args = parse_args()
    if not metric_name_is_safe(args.metric_name):
        raise SystemExit("Metric name may contain only letters, digits, underscores, dots, dashes, and µ.")

    root = Path(args.directory).resolve()
    root.mkdir(parents=True, exist_ok=True)
    refuse_overwrite(root, args.force)

    (root / "autoresearch.md").write_text(render_md(args), encoding="utf-8")
    write_executable(root / "autoresearch.sh", render_runner(args))
    if args.guard_command:
        write_executable(root / "autoresearch.checks.sh", render_checks(args))
    (root / "autoresearch.ideas.md").write_text("# Autoresearch Ideas\n\n", encoding="utf-8")

    config = {
        "type": "config",
        "goal": args.goal,
        "metric_name": args.metric_name,
        "metric_unit": args.metric_unit,
        "direction": args.direction,
        "scope": args.scope,
        "verify_command": "./autoresearch.sh",
        "guard_command": "./autoresearch.checks.sh" if args.guard_command else None,
        "max_iterations": args.max_iterations,
        "created_at": now_iso(),
    }
    with (root / "autoresearch.jsonl").open("w", encoding="utf-8") as handle:
        handle.write(json.dumps(config, sort_keys=True) + "\n")

    print(f"Created autoresearch session in {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
