"""Curated Farplane lifecycle graph catalog data."""

from __future__ import annotations

TARGET_SKILLS = [
    "init-advisor",
    "metric-advisor",
    "goal-advisor",
    "harness-advisor",
    "proof-advisor",
    "impl-plan",
    "leverage-advisor",
    "pulse-update",
    "interval-update",
    "automation-advisor",
    "doc-advisor",
    "manage-wiki",
    "optimize-harness",
    "skill-creator",
    "skill-maintenance",
    "consolidate",
    "eval",
    "qa",
    "review",
]

CURATED_FILES = {
    "AGENTS.md": ("file", "Project operating policy", ["project", "policy"]),
    "README.md": ("file", "Project README", ["project", "docs"]),
    "ARCHITECTURE.md": ("file", "Project architecture", ["project", "docs"]),
    "PROJECT_RULES.md": ("file", "Project rules", ["project", "policy"]),
    "farplane/README.md": ("file", "Framework local README", ["farplane", "tracked-config"]),
    "farplane/manifest.json": ("file", "Framework manifest", ["farplane", "tracked-config"]),
    "farplane/harness.yaml": ("file", "Project harness", ["farplane", "tracked-config"]),
    "farplane/metrics.yaml": ("file", "Project objective and metric contract", ["farplane", "objectives", "metrics", "tracked-config"]),
    "farplane/automations.toml": ("file", "Reviewed automation prompts", ["farplane", "automation"]),
    "farplane/bindings.yaml": ("file", "Project bindings", ["farplane", "tracked-config"]),
    ".agents/skills/README.md": ("file", "Local project skill home", ["agents", "skills", "tracked-config"]),
    "farplane/pm.json": ("file", "PM UI thread grouping", ["farplane", "pm-ui"]),
    ".farplane/reports/pulse/<timestamp>.md": ("report", "Pulse reports", ["runtime", "pulse"]),
    ".farplane/reports/interval/<interval_id>/<timestamp>.md": ("report", "Interval reports", ["runtime", "interval"]),
    ".farplane/automation/decisions.jsonl": ("state", "Pulse decisions", ["runtime", "pulse"]),
    ".farplane/automation/rewards.jsonl": ("state", "Pulse rewards", ["runtime", "pulse"]),
    "tickets/TASK-*/ticket.md": ("ticket", "Ticket contract", ["ticket", "goal-packet"]),
    "tickets/TASK-*/program.md": ("ticket", "Goal Packet program", ["ticket", "goal-packet"]),
    "tickets/TASK-*/progress.md": ("ticket", "Goal Packet progress", ["ticket", "goal-packet"]),
    "tickets/TASK-*/artifacts/": ("ticket", "Ticket proof artifacts", ["ticket", "proof"]),
    "docs/MEMORY.md": ("doc", "Durable memory", ["docs", "memory"]),
    "docs/HISTORY.md": ("doc", "Project history", ["docs", "memory"]),
    ".farplane/entities/*.md": ("doc", "Canonical Wiki entity articles", ["wiki", "entities"]),
    "docs/farplane-framework/lifecycle.md": ("doc", "Lifecycle hub", ["docs", "framework"]),
    "docs/farplane-framework/graph-contract.md": ("doc", "Lifecycle graph contract", ["docs", "framework", "graph"]),
    "docs/farplane-framework/hooks-and-runtime.md": ("doc", "Hooks and runtime", ["docs", "framework", "hooks"]),
    "hooks.json": ("file", "Codex hook config", ["hooks", "runtime"]),
}

CURATED_EDGES = [
    ("skill:init-advisor", "file:AGENTS.md", "writes", "docs/farplane-framework/init-advisor-critical-path.md"),
    ("skill:init-advisor", "file:PROJECT_RULES.md", "writes", "docs/farplane-framework/init-advisor-critical-path.md"),
    ("skill:init-advisor", "file:ARCHITECTURE.md", "writes", "docs/farplane-framework/init-advisor-critical-path.md"),
    ("skill:init-advisor", "file:farplane/manifest.json", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:init-advisor", "file:farplane/harness.yaml", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:init-advisor", "file:farplane/metrics.yaml", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:init-advisor", "file:farplane/automations.toml", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:init-advisor", "file:.agents/skills/README.md", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:init-advisor", "file:farplane/pm.json", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:harness-creator", "file:.agents/skills/README.md", "updates", "docs/farplane-framework/project-files.md"),
    ("skill:metric-advisor", "file:farplane/metrics.yaml", "updates", "docs/farplane-framework/lifecycle.md"),
    ("file:farplane/metrics.yaml", "skill:goal-advisor", "informs", "docs/farplane-framework/lifecycle.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/ticket.md", "writes", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/program.md", "writes", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/progress.md", "writes", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("ticket:tickets/TASK-*/ticket.md", "skill:impl-plan", "triggers", "tickets/TASK-0213/ticket.md"),
    ("ticket:tickets/TASK-*/program.md", "runtime:native-codex-goal", "triggers", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("runtime:native-codex-goal", "ticket:tickets/TASK-*/progress.md", "writes", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("runtime:native-codex-goal", "ticket:tickets/TASK-*/artifacts/", "writes", "docs/features/FEAT-0029-goal-packet-architecture-for-native-codex-goals.md"),
    ("file:farplane/automations.toml", "automation:pulse", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("file:farplane/automations.toml", "automation:daily-interval", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("file:farplane/automations.toml", "automation:weekly-interval", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("automation:pulse", "skill:pulse-update", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("automation:daily-interval", "skill:interval-update", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("automation:weekly-interval", "skill:interval-update", "triggers", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("skill:pulse-update", "report:.farplane/reports/pulse/<timestamp>.md", "writes", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("skill:interval-update", "report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "writes", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:metric-advisor", "routes_to", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:leverage-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:leverage-advisor", "skill:harness-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:harness-advisor", "skill:proof-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:proof-advisor", "skill:eval", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:proof-advisor", "skill:qa", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:proof-advisor", "skill:review", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:harness-advisor", "skill:goal-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:pulse-update", "state:.farplane/automation/decisions.jsonl", "writes", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("report:.farplane/reports/pulse/<timestamp>.md", "skill:interval-update", "consumes", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:pulse-update", "consumes", "docs/features/FEAT-0065-pulse-and-interval-automation.md"),
    ("skill:doc-advisor", "file:README.md", "updates", "docs/features/FEAT-0060-registry-backed-documentation-os.md"),
    ("skill:manage-wiki", "doc:.farplane/entities/*.md", "updates", "docs/systems/wiki.md"),
    ("skill:consolidate", "doc:docs/MEMORY.md", "updates", "skills/consolidate/SKILL.md"),
    ("skill:skill-maintenance", "skill:eval", "routes_to", "skills/skill-maintenance/SKILL.md"),
]

FSA_SPECS = [
    (
        "project_initialization",
        "Project initialization",
        [
            "operator intent",
            "init advisor target bound",
            "project substrate written",
            "framework config written",
            "readiness audited",
            "metric objectives shaped",
            "goal advisor handoff ready",
        ],
        ["goal advisor handoff ready"],
    ),
    (
        "automation_activation",
        "Automation activation",
        [
            "automation prompts reviewed",
            "pulse thread created",
            "pulse heartbeat attached",
            "daily interval cron created",
            "weekly interval cron created",
            "pm json grouped",
        ],
        ["pm json grouped"],
    ),
    (
        "ticket_goal_execution",
        "Ticket to native Goal execution",
        [
            "ticket selected",
            "implementation plan prepared",
            "goal packet written",
            "native goal started",
            "build executed",
            "qa proof captured",
            "demo proof captured when required",
            "review passed",
            "ticket closed out",
        ],
        ["ticket closed out"],
    ),
    (
        "interval_knowledge_phase",
        "Interval knowledge phase",
        [
            "interval evidence window bound",
            "candidate lanes extracted",
            "weekly draft upserted",
            "daily zero-promotion or weekly dispositions selected",
            "interval report finalized",
            "daily task progress or weekly promotions applied",
            "knowledge receipt written",
            "current or next weekly draft ready",
        ],
        ["current or next weekly draft ready"],
    ),
    (
        "self_update_loop",
        "Weekly self-update loop",
        [
            "weekly report written",
            "goals delta classified",
            "leverage bets scored",
            "proof route selected",
            "operator approval or source gap recorded",
            "horizon delta applied when approved",
            "goal advisor handoff compiled",
            "pulse executes bounded work",
            "reward signal recorded",
            "next weekly review reads outcomes",
        ],
        ["next weekly review reads outcomes"],
    ),
]
