"""Curated Farplane lifecycle graph catalog data."""

from __future__ import annotations

TARGET_SKILLS = [
    "deep-init-project",
    "horizon-advisor",
    "goal-advisor",
    "harness-advisor",
    "proof-advisor",
    "impl-plan",
    "leverage-advisor",
    "pulse-update",
    "interval-update",
    "automation-advisor",
    "update-memory",
    "learning-drain",
    "optimize-harness",
    "skill-creator",
    "skill-maintenance",
    "knowledge-tidier",
    "eval",
    "qa",
    "review",
]

CURATED_FILES = {
    "AGENTS.md": ("file", "Project operating policy", ["project", "policy"]),
    "README.md": ("file", "Project README", ["project", "docs"]),
    "ARCHITECTURE.md": ("file", "Project architecture", ["project", "docs"]),
    "PROJECT_RULES.md": ("file", "Project rules", ["project", "policy"]),
    "farplane/README.md": ("file", "Framework local README", ["farplane", "tracked-config"]),
    "farplane/manifest.json": ("file", "Framework manifest", ["farplane", "tracked-config"]),
    "farplane/harness.md": ("file", "Project harness", ["farplane", "tracked-config"]),
    "farplane/goals.md": ("file", "Project goals", ["farplane", "goals", "tracked-config"]),
    "farplane/automations.md": ("file", "Reviewed automation prompts", ["farplane", "automation"]),
    "farplane/bindings.md": ("file", "Project bindings", ["farplane", "tracked-config"]),
    "farplane/evals.md": ("file", "Project eval policy", ["farplane", "proof"]),
    "farplane/pm.json": ("file", "PM UI thread grouping", ["farplane", "pm-ui"]),
    ".farplane/state/run-ledger.json": ("state", "Run ledger", ["runtime"]),
    ".farplane/reports/pulse/<timestamp>.md": ("report", "Pulse reports", ["runtime", "pulse"]),
    ".farplane/reports/interval/<interval_id>/<timestamp>.md": ("report", "Interval reports", ["runtime", "interval"]),
    ".farplane/automation/decisions.jsonl": ("state", "Pulse decisions", ["runtime", "pulse"]),
    ".farplane/automation/rewards.jsonl": ("state", "Pulse rewards", ["runtime", "pulse"]),
    ".farplane/automation/action-outcomes.jsonl": ("state", "Pulse action outcomes", ["runtime", "pulse"]),
    ".farplane/automation/spawned-threads.jsonl": ("state", "Spawned thread ledger", ["runtime", "pulse"]),
    "tickets/TASK-*/ticket.md": ("ticket", "Ticket contract", ["ticket", "goal-packet"]),
    "tickets/TASK-*/program.md": ("ticket", "Goal Packet program", ["ticket", "goal-packet"]),
    "tickets/TASK-*/progress.md": ("ticket", "Goal Packet progress", ["ticket", "goal-packet"]),
    "tickets/TASK-*/artifacts/": ("ticket", "Ticket proof artifacts", ["ticket", "proof"]),
    "docs/MEMORY.md": ("doc", "Durable memory", ["docs", "memory"]),
    "docs/HISTORY.md": ("doc", "Project history", ["docs", "memory"]),
    "docs/LESSONS.md": ("doc", "Distilled lessons", ["docs", "memory"]),
    "docs/TROUBLES.md": ("doc", "Raw trouble log", ["docs", "memory"]),
    "docs/farplane-framework/lifecycle.md": ("doc", "Lifecycle hub", ["docs", "framework"]),
    "docs/farplane-framework/graph-contract.md": ("doc", "Lifecycle graph contract", ["docs", "framework", "graph"]),
    "docs/farplane-framework/hooks-and-runtime.md": ("doc", "Hooks and runtime", ["docs", "framework", "hooks"]),
    "hooks.json": ("file", "Codex hook config", ["hooks", "runtime"]),
}

CURATED_EDGES = [
    ("skill:deep-init-project", "file:AGENTS.md", "writes", "docs/farplane-framework/deep-init-critical-path.md"),
    ("skill:deep-init-project", "file:PROJECT_RULES.md", "writes", "docs/farplane-framework/deep-init-critical-path.md"),
    ("skill:deep-init-project", "file:ARCHITECTURE.md", "writes", "docs/farplane-framework/deep-init-critical-path.md"),
    ("skill:deep-init-project", "file:farplane/manifest.json", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:deep-init-project", "file:farplane/harness.md", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:deep-init-project", "file:farplane/goals.md", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:deep-init-project", "file:farplane/automations.md", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:deep-init-project", "file:farplane/pm.json", "writes", "docs/farplane-framework/project-files.md"),
    ("skill:horizon-advisor", "file:farplane/goals.md", "updates", "docs/farplane-framework/lifecycle.md"),
    ("file:farplane/goals.md", "skill:goal-advisor", "triggers", "docs/specs/goal-loop-contract.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/ticket.md", "writes", "docs/specs/goal-loop-contract.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/program.md", "writes", "docs/specs/goal-loop-contract.md"),
    ("skill:goal-advisor", "ticket:tickets/TASK-*/progress.md", "writes", "docs/specs/goal-loop-contract.md"),
    ("ticket:tickets/TASK-*/ticket.md", "skill:impl-plan", "triggers", "tickets/TASK-0213/ticket.md"),
    ("ticket:tickets/TASK-*/program.md", "runtime:native-codex-goal", "triggers", "docs/specs/goal-loop-contract.md"),
    ("runtime:native-codex-goal", "ticket:tickets/TASK-*/progress.md", "writes", "docs/specs/goal-loop-contract.md"),
    ("runtime:native-codex-goal", "ticket:tickets/TASK-*/artifacts/", "writes", "docs/specs/goal-loop-contract.md"),
    ("file:farplane/automations.md", "automation:pulse", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("file:farplane/automations.md", "automation:daily-interval", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("file:farplane/automations.md", "automation:weekly-interval", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("automation:pulse", "skill:pulse-update", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("automation:daily-interval", "skill:interval-update", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("automation:weekly-interval", "skill:interval-update", "triggers", "docs/specs/steer-pulse-automation.md"),
    ("skill:pulse-update", "report:.farplane/reports/pulse/<timestamp>.md", "writes", "docs/specs/steer-pulse-automation.md"),
    ("skill:interval-update", "report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "writes", "docs/specs/steer-pulse-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:horizon-advisor", "routes_to", "docs/specs/steer-pulse-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:leverage-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:leverage-advisor", "skill:harness-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:harness-advisor", "skill:proof-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:proof-advisor", "skill:eval", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:proof-advisor", "skill:qa", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:proof-advisor", "skill:review", "routes_to", "skills/proof-advisor/SKILL.md"),
    ("skill:harness-advisor", "skill:goal-advisor", "routes_to", "docs/farplane-framework/lifecycle.md"),
    ("skill:pulse-update", "state:.farplane/automation/decisions.jsonl", "writes", "docs/specs/steer-pulse-automation.md"),
    ("report:.farplane/reports/pulse/<timestamp>.md", "skill:interval-update", "consumes", "docs/specs/steer-pulse-automation.md"),
    ("report:.farplane/reports/interval/<interval_id>/<timestamp>.md", "skill:pulse-update", "consumes", "docs/specs/steer-pulse-automation.md"),
    ("doc:docs/TROUBLES.md", "skill:learning-drain", "triggers", "docs/specs/filesystem-lifecycle.md"),
    ("doc:docs/LESSONS.md", "skill:learning-drain", "triggers", "docs/specs/filesystem-lifecycle.md"),
    ("skill:learning-drain", "skill:skill-maintenance", "routes_to", "skills/learning-drain/SKILL.md"),
    ("skill:update-memory", "doc:docs/MEMORY.md", "updates", "docs/specs/filesystem-lifecycle.md"),
    ("skill:knowledge-tidier", "doc:docs/MEMORY.md", "updates", "docs/farplane-framework/hooks-and-runtime.md"),
    ("skill:skill-maintenance", "skill:eval", "routes_to", "skills/skill-maintenance/SKILL.md"),
]

FSA_SPECS = [
    (
        "project_initialization",
        "Project initialization",
        [
            "operator intent",
            "deep init target bound",
            "project substrate written",
            "framework config written",
            "readiness audited",
            "horizon goals shaped",
            "goal advisor handoff ready",
        ],
        ["goal advisor handoff ready"],
    ),
    (
        "automation_activation",
        "Automation activation",
        [
            "automation prompts reviewed",
            "pulse thread created",
            "pulse heartbeat attached",
            "daily interval cron created",
            "weekly interval cron created",
            "pm json grouped",
        ],
        ["pm json grouped"],
    ),
    (
        "ticket_goal_execution",
        "Ticket to native Goal execution",
        [
            "ticket selected",
            "implementation plan prepared",
            "goal packet written",
            "native goal started",
            "build executed",
            "qa proof captured",
            "demo proof captured when required",
            "review passed",
            "ticket closed out",
        ],
        ["ticket closed out"],
    ),
    (
        "memory_drain_upkeep",
        "Memory and drain upkeep",
        [
            "raw signals accumulated",
            "drain window selected",
            "rows deduped and scored",
            "owner surfaces chosen",
            "memory or docs updated",
            "skill hardening routed",
            "eval or review evidence recorded",
            "processed state written",
        ],
        ["processed state written"],
    ),
    (
        "self_update_loop",
        "Weekly self-update loop",
        [
            "weekly report written",
            "goals delta classified",
            "leverage bets scored",
            "proof route selected",
            "operator approval or source gap recorded",
            "horizon delta applied when approved",
            "goal advisor handoff compiled",
            "pulse executes bounded work",
            "reward signal recorded",
            "next weekly review reads outcomes",
        ],
        ["next weekly review reads outcomes"],
    ),
]
